# Generated by Django 3.2.13 on 2022-06-29 20:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0003_auto_20220625_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='favorites',
            field=models.ManyToManyField(related_name='song_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='song',
            name='likes',
            field=models.ManyToManyField(related_name='song_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
